# Generated by Django 3.2.13 on 2022-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevvnQuanhuyen',
            fields=[
                ('maqh', models.CharField(db_collation='utf8_general_ci', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('type', models.CharField(db_collation='utf8_general_ci', max_length=30)),
                ('matp', models.CharField(db_collation='utf8_general_ci', max_length=5)),
            ],
            options={
                'db_table': 'devvn_quanhuyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevvnTinhthanhpho',
            fields=[
                ('matp', models.CharField(db_collation='utf8_general_ci', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('type', models.CharField(db_collation='utf8_general_ci', max_length=30)),
                ('slug', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'devvn_tinhthanhpho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevvnXaphuongthitran',
            fields=[
                ('xaid', models.CharField(db_collation='utf8_general_ci', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('type', models.CharField(db_collation='utf8_general_ci', max_length=30)),
                ('maqh', models.CharField(db_collation='utf8_general_ci', max_length=5)),
            ],
            options={
                'db_table': 'devvn_xaphuongthitran',
                'managed': False,
            },
        ),
    ]
