# Generated by Django 3.2.13 on 2022-06-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_devvnquanhuyen_devvntinhthanhpho_devvnxaphuongthitran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nguoidang',
            fields=[
                ('id_nguoidang', models.AutoField(primary_key=True, serialize=False)),
                ('nguoi_dang', models.TextField(blank=True, null=True)),
                ('sdt', models.TextField(blank=True, null=True)),
                ('so_like', models.IntegerField()),
            ],
            options={
                'db_table': 'nguoidang',
                'managed': False,
            },
        ),
    ]
